name: main

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: |
          rebar3 compile
          rebar3 shell --eval "yolo:abc(), erlang:halt()"

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: |
          rebar3 compile
          rebar3 shell --eval "yolo:abc(), erlang:halt()"

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: erlangsters/setup-erlang@v1
        with:
          erlang-version: 28
          install-rebar3: true
      - run: |
          rebar3 compile
          rebar3 shell --eval "yolo:abc(), erlang:halt()"
